name: Publish Mkdocs

on:
  # Trigger the workflow on push
  push:
    branches:
      - main
    
  # Allow manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - name: Cache MkDocs dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
            
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material \
                      mkdocs-roamlinks-plugin \
                      mkdocs-git-revision-date-localized-plugin \
                      mkdocs-literate-nav
      
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
